version: '3.9'
services:
  felandrix:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=felipe
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=felandrix
    ports:
      - "5432:5432"
    volumes:
      - /Users/felipe/postgres/felandrix:/var/lib/postgresql/data