GET {{base_path}}/cards
Accept: application/json

###

GET {{base_path}}/cards/a8066aa7-65fe-42dc-9d65-6ead29e00701
Accept: application/json

###

POST {{base_path}}/cards
Content-Type: application/json

{
  "card_name": "XP",
  "card_status": true,
  "card_due_day": 27
}
###

PATCH {{base_path}}/cards/88673a2f-62fd-4e54-bf8d-d59b959e0548
Content-Type: application/json

{
  "card_status": false
}

###

PUT {{base_path}}/cards/88673a2f-62fd-4e54-bf8d-d59b959e0548
Content-Type: application/json

{
  "card_status": true,
  "card_name": "XP",
  "card_due_day": 27
}

###



